First networking scripts, rsync and dropbear

diff --git a/generic/initramfs/init b/generic/initramfs/init
--- a/generic/initramfs/init
+++ b/generic/initramfs/init
@@ -1,8 +1,178 @@
 #!/bin/sh
 
-error() {
-	echo "Error: $1"
+PATH=/bin:/sbin
+IF=eth0
+
+msg() {
+	echo "[*] $@"
+}
+
+shell() {
+	echo ""
+	echo "Values:"
+	echo "CMDLINE = \"${CMDLINE}\""
+	echo "SERVER  = \"${SERVER}\""
+	echo "HOOKS   = \"${HOOKS}\""
+	echo "IF      = \"${IF}\""
+	echo "MAC     = \"${MAC}\""
+	echo ""
+	echo "You are being dropped to a shell"
+	echo "Continue booting by typing \"exit\""
 	/bin/sh
 }
 
-/bin/sh
+start_process() {
+	echo -n "[*] $1... "
+}
+
+end_process() {
+	echo "done."
+}
+
+error_msg() {
+	echo ""
+	echo "[!] $@"
+}
+
+error_process() {
+	echo "FAILED!"
+	shell
+}
+
+error() {
+	error_msg "$1"
+	shell
+}
+
+break_on_hook() {
+	if [ $(echo $HOOKS | grep $1 | wc -l) -eq 1 ] ; then
+		msg "Hook \"$1\" found"
+		shell
+	else
+		msg "Hook \"$1\" skipped"
+	fi
+
+}
+
+parse() {
+	CMDLINE=$(cat /proc/cmdline)
+	for PARAM in ${CMDLINE}; do
+		case ${PARAM} in
+			server=*)
+				SERVER=${PARAM#server=}
+				;;
+			hooks=*)
+				HOOKS=${PARAM#hooks=}
+				;;
+			interface=*)
+				IF=${PARAM#interface=}
+				;;
+			mac=*)
+				MAC=${PARAM#mac=}
+				;;
+			ip=*)
+				IP=${PARAM#ip=}
+				;;
+			ifmod=*) 
+				MOD=${PARAM#ifmod=}
+				;;
+		esac
+	done
+}
+
+obtain_mac() {
+	if [ -z "${MAC}" ] ; then
+		MAC=$(ifconfig ${IF} | head -n1 | grep -Eo "[0-9][:a-f0-9]+")
+	fi
+}
+
+config_network() {
+	modprobe ${MOD} || return 1
+	obtain_mac 
+	ifconfig ${IF} ${IP} || return 1
+}
+
+load_config(){
+	rsync -vvrae dbclient ${SERVER}/configs/${MAC}/config /tmp 
+}
+
+check_environment() {
+	if [ -z "${SERVER}" ] ; then 
+		error_msg  "No server specified"
+		echo "No server path was specified."
+		echo "I don't know what to sync with"
+		echo "Please edit the local grub.conf (or menu.lst)"
+		echo "or hit [e] at the bootloader's screen"
+		echo "and pass server=user@ip:/path"
+		return 1
+	fi
+	
+	if [ -z "${IP}" ] ; then 
+		error_msg  "No IP defined"
+		echo "No IP for this machine was specified."
+		echo "Can't access the network."
+		echo "Please edit the local grub.conf (or menu.lst)"
+		echo "or hit [e] at the bootloader's screen"
+		echo "and pass ip=xxx.xxx.xxx.xxx"
+		return 1
+	fi
+
+	if [ -z "${MOD}" ] ; then
+		error_msg  "No ethernet module specified"
+		echo "No module for the ethernet card was specified."
+		echo "Can't access the network."
+		echo "Please edit the local grub.conf (or menu.lst)"
+		echo "or hit [e] at the bootloader's screen"
+		echo "and pass ifmod=modulename"
+		return 1
+	fi
+}
+
+hang() {
+	error_msg "Booting failed"
+	echo ""
+	echo "It seems like the remote filesystem"
+	echo "was not successfully synchronized"
+	echo "with the local hard disk."
+	echo "The system has been prepared to be powered off."
+	echo "Check your configurations and paths."
+	while true; do
+		shell
+	done
+}
+
+
+msg "Setting up presync environment"
+/bin/busybox mount -t proc none /proc || error "Mounting procfs"
+/bin/busybox mount -t sysfs none /sys || error "Mounting sysfs"
+start_process "Creating devices"
+/bin/busybox mdev -s  || error_process 
+end_process
+
+start_process "Populating /bin"
+/bin/busybox --install || error_process
+end_process
+
+start_process "Parsing commandline"
+parse || error_process
+end_process
+
+break_on_hook "early"
+
+start_process "Sanitizing"
+check_environment || shell
+end_process
+
+break_on_hook "network"
+
+start_process "Configuring network"
+config_network
+end_process
+
+break_on_hook "config"
+
+start_process "Loading configuration"
+load_config
+end_process
+
+hang
